name: CI

on:
  pull_request_target:
    branches: [master]
  workflow_dispatch:

jobs:
  percy-check:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.repository_owner == github.actor }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn
      - name: Waiting for Netlify Preview
        uses: kamranayub/wait-for-netlify-action@v2.0.3
        id: wait-for-netflify-preview
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          site_name: 'oskar-dev'
          max_timeout: 60
        env:
          NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}
      - name: Create Percy snapshots file
        uses: 'finnp/create-file-action@master'
        env:
          FILE_NAME: 'snapshots.yml'
          FILE_DATA: '- ${{ steps.wait-for-netflify-preview.outputs.url }}'
      - name: Run Percy
        run: npx percy snapshot snapshots.yml
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
      - name: Auto merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.MY_TOKEN }}
